version: '3'
services:
  nginx:
    volumes:
      - ./client/src:/var/www/sharks
  
  app:
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: npm debug
