version: '3'
services:
  nginx:
    build: client/
    volumes:
      - ./client/src:/var/www/sharks
    ports:
      - 8080:80
    depends_on:
      - app
  
  app:
    build: server/
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - NODE_PORT=9090
    volumes:
      - ./server:/usr/src/app
    expose:
      - 9090
#    tty: true
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.8
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    expose:
      - 27017

  admin:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
  
volumes:
  mongodb:
  mongodb_config: